name: scsaworkflow
channels:
  - ohsu-comp-bio
  - conda-forge
  - defaults
dependencies:
  - python=3.7.13
  - pip
  - mamba
  - matplotlib
  - squidpy
  - pandas
  - jupyter
  - cookiecutter
  - pip:
    - phenograph==1.5.7
    - poetry